package ch.ansermgw.angryword.provider;

import ch.ansermgw.angryword.activities.Play;
import ch.ansermgw.angryword.resource.VocabularyResource;
import ch.ansermgw.angryword.resource.WordResource;

import java.util.ArrayList;
import java.util.List;

public class VocabularyProvider {
    private static VocabularyProvider instance;
    private final List<VocabularyResource> vocabularies;

    private VocabularyProvider() {
        vocabularies = new ArrayList<>();
        WordResource word;

        VocabularyResource vocabulary = new VocabularyResource("money");
        word = new WordResource("la banque", "the bank");
        vocabulary.addWord(word);
        word = new WordResource("l''argent liquide", "cash");
        vocabulary.addWord(word);
        word = new WordResource("le paiement", "payment");
        vocabulary.addWord(word);
        word = new WordResource("un carnet de chèques", "checkbook");
        vocabulary.addWord(word);
        word = new WordResource("déposer de l''argent", "to deposit money");
        vocabulary.addWord(word);
        word = new WordResource("prêter de l''argent", "to borrow money");
        vocabulary.addWord(word);
        word = new WordResource("les services financiers", "financial services");
        vocabulary.addWord(word);
        word = new WordResource("la commission", "commission");
        vocabulary.addWord(word);
        word = new WordResource("un investissement", "an investment");
        vocabulary.addWord(word);
        word = new WordResource("un virement", "transfer");
        vocabulary.addWord(word);
        word = new WordResource("la gestion de l''argent", "money management");
        vocabulary.addWord(word);
        word = new WordResource("une transaction", "a transaction");
        vocabulary.addWord(word);
        word = new WordResource("un guichet automatique", "ATM machine");
        vocabulary.addWord(word);
        word = new WordResource("attendre dans la queue", "to wait in line");
        vocabulary.addWord(word);
        word = new WordResource("une carte bancaire", "banking/ATM card");
        vocabulary.addWord(word);
        word = new WordResource("faire des économies", "to save money");
        vocabulary.addWord(word);
        word = new WordResource("le montant", "sum/total amount");
        vocabulary.addWord(word);
        word = new WordResource("un compte-chèques", "checking account");
        vocabulary.addWord(word);
        word = new WordResource("l''argent", "money");
        vocabulary.addWord(word);
        word = new WordResource("les fonds", "funds");
        vocabulary.addWord(word);
        word = new WordResource("un chèque", "check");
        vocabulary.addWord(word);
        word = new WordResource("un dépôt", "deposit");
        vocabulary.addWord(word);
        word = new WordResource("le crédit", "credit");
        vocabulary.addWord(word);
        word = new WordResource("les marchés financiers", "financial markets");
        vocabulary.addWord(word);
        word = new WordResource("la clientèle", "clientele");
        vocabulary.addWord(word);
        word = new WordResource("les frais", "fees");
        vocabulary.addWord(word);
        word = new WordResource("une institution financière", "financial institution");
        vocabulary.addWord(word);
        word = new WordResource("le taux d''intérêt", "interest rate");
        vocabulary.addWord(word);
        word = new WordResource("la monnaie", "currency");
        vocabulary.addWord(word);
        word = new WordResource("le bilan", "balance");
        vocabulary.addWord(word);
        word = new WordResource("prendre un numéro", "to take a number");
        vocabulary.addWord(word);
        word = new WordResource("une carte de crédit", "credit card");
        vocabulary.addWord(word);
        word = new WordResource("un emprunt", "a loan");
        vocabulary.addWord(word);
        word = new WordResource("retirer de l''argent", "to take out money");
        vocabulary.addWord(word);
        word = new WordResource("un compte d''épargne", "savings account");
        vocabulary.addWord(word);
        word = new WordResource("un distributeur automatique", "ATM machine");
        vocabulary.addWord(word);
        word = new WordResource("un reçu", "receipt");
        vocabulary.addWord(word);
        vocabularies.add(vocabulary);

        vocabulary = new VocabularyResource("meubles");
        word = new WordResource("une table", "a table");
        vocabulary.addWord(word);
        word = new WordResource("une chaise", "a chair");
        vocabulary.addWord(word);
        word = new WordResource("une bibliothèque", "a bookcase");
        vocabulary.addWord(word);
        word = new WordResource("une table basse", "a coffee table");
        vocabulary.addWord(word);
        word = new WordResource("une cheminée", "a fireplace");
        vocabulary.addWord(word);
        word = new WordResource("une table de chevet", "a bedside table");
        vocabulary.addWord(word);
        word = new WordResource("une étagère", "a shelf");
        vocabulary.addWord(word);
        word = new WordResource("une armoire", "a wardrobe");
        vocabulary.addWord(word);
        word = new WordResource("une commode", "a dresser");
        vocabulary.addWord(word);
        word = new WordResource("une moquette", "a carpet");
        vocabulary.addWord(word);
        word = new WordResource("un siège", "a seat");
        vocabulary.addWord(word);
        word = new WordResource("un tabouret", "a stool");
        vocabulary.addWord(word);
        word = new WordResource("un placard", "a cupboard");
        vocabulary.addWord(word);
        word = new WordResource("un tiroir", "a drawer");
        vocabulary.addWord(word);
        word = new WordResource("un fauteuil", "a armchair");
        vocabulary.addWord(word);
        word = new WordResource("un lit", "a bed");
        vocabulary.addWord(word);
        word = new WordResource("un bureau", "a desk");
        vocabulary.addWord(word);
        word = new WordResource("un miroir", "a mrror");
        vocabulary.addWord(word);
        word = new WordResource("un meuble", "a piece of furniture");
        vocabulary.addWord(word);
        word = new WordResource("un oreiller", "a pillow");
        vocabulary.addWord(word);
        vocabularies.add(vocabulary);

        vocabulary = new VocabularyResource("colors");
        word = new WordResource("blanc", "white");
        vocabulary.addWord(word);
        word = new WordResource("bleu clair", "light blue");
        vocabulary.addWord(word);
        word = new WordResource("multicolore", "muli-colored");
        vocabulary.addWord(word);
        word = new WordResource("gris", "grey");
        vocabulary.addWord(word);
        word = new WordResource("vert", "green");
        vocabulary.addWord(word);
        word = new WordResource("noir", "black");
        vocabulary.addWord(word);
        word = new WordResource("argenté", "silver");
        vocabulary.addWord(word);
        word = new WordResource("jaune", "yellow");
        vocabulary.addWord(word);
        word = new WordResource("orange", "orange");
        vocabulary.addWord(word);
        word = new WordResource("bleu", "blue");
        vocabulary.addWord(word);
        word = new WordResource("bleu foncé", "dark blue");
        vocabulary.addWord(word);
        word = new WordResource("rose", "pink");
        vocabulary.addWord(word);
        word = new WordResource("rouge", "red");
        vocabulary.addWord(word);
        word = new WordResource("marron", "brown");
        vocabulary.addWord(word);
        word = new WordResource("violet", "purple");
        vocabulary.addWord(word);
        word = new WordResource("beige", "beige");
        vocabulary.addWord(word);
        word = new WordResource("turquoise", "turquoise");
        vocabulary.addWord(word);
        word = new WordResource("doré", "golden");
        vocabulary.addWord(word);
        vocabularies.add(vocabulary);

        vocabulary = new VocabularyResource("family");
        word = new WordResource("le père", "the father");
        vocabulary.addWord(word);
        word = new WordResource("les parents", "the parents");
        vocabulary.addWord(word);
        word = new WordResource("la sœur", "the sister");
        vocabulary.addWord(word);
        word = new WordResource("la fille", "the daughter");
        vocabulary.addWord(word);
        word = new WordResource("le bébé", "the baby");
        vocabulary.addWord(word);
        word = new WordResource("la femme", "the wife");
        vocabulary.addWord(word);
        word = new WordResource("la fiancée", "the fiancée");
        vocabulary.addWord(word);
        word = new WordResource("la grand-mère", "the grandmother");
        vocabulary.addWord(word);
        word = new WordResource("les petits-enfants", "the grandchildren");
        vocabulary.addWord(word);
        word = new WordResource("la tante", "the aunt");
        vocabulary.addWord(word);
        word = new WordResource("la nièce", "the niece");
        vocabulary.addWord(word);
        word = new WordResource("la belle-mère", "the step mother");
        vocabulary.addWord(word);
        word = new WordResource("la cousine", "the cousin (female)");
        vocabulary.addWord(word);
        word = new WordResource("la belle-sœur", "sister in-law");
        vocabulary.addWord(word);
        word = new WordResource("la mère", "the mother");
        vocabulary.addWord(word);
        word = new WordResource("le frère", "the brother");
        vocabulary.addWord(word);
        word = new WordResource("le fils", "the son");
        vocabulary.addWord(word);
        word = new WordResource("l’enfant", "the child");
        vocabulary.addWord(word);
        word = new WordResource("le mari", "the husband");
        vocabulary.addWord(word);
        word = new WordResource("le fiancé", "the fiancé");
        vocabulary.addWord(word);
        word = new WordResource("le grand-père", "the grandfather");
        vocabulary.addWord(word);
        word = new WordResource("les grand-parents", "the grandparents");
        vocabulary.addWord(word);
        word = new WordResource("l’oncle", "the uncle");
        vocabulary.addWord(word);
        word = new WordResource("le neveu", "the nephew");
        vocabulary.addWord(word);
        word = new WordResource("le beau-père", "the step father");
        vocabulary.addWord(word);
        word = new WordResource("le cousin", "the cousin (male)");
        vocabulary.addWord(word);
        word = new WordResource("le beau-frère", "brother in-law");
        vocabulary.addWord(word);
        word = new WordResource("le beau-père", "father in-law");
        vocabulary.addWord(word);
        vocabularies.add(vocabulary);
    }

    public static VocabularyProvider getInstance() {
        if (instance == null)
            VocabularyProvider.instance = new VocabularyProvider();

        return instance;
    }

    public VocabularyResource getRandomVocabulary() {
        return vocabularies.get(Play.rand.nextInt(vocabularies.size()));
    }
}
